[project]
name = "textual-forms"
version = "0.7.10"
description = "A prototype forms package for textual"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [ "pytest-asyncio>=1.0.0", "textual>=3.5.0",]
[[project.authors]]
name = "Steve Holden"
email = "steve@holdenweb.com"

[dependency-groups]
dev = [ "pytest>=8.3.5", "pytest-asyncio>=0.26.0", "pytest-cov>=6.1.1", "ruff>=0.11.7", "semver>=3.0.4", "textual-dev>=1.7.0", "toml>=0.10.2",]
docs = [ "mkdocs>=1.6.1",]

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
forms-app = "textual_forms.demo:main"

[tool.uv]
[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"

[tool.hatch.build.targets.sdist]
only-include = [ "src/textual_forms",]

[tool.hatch.build.targets.sdist.sources]
"src/textual_forms" = "textual_forms"

[tool.hatch.build.targets.wheel.sources]
"src/textual_forms" = "textual_forms"
